export const SliderData = [
    {
        image:'https://i.imgur.com/hINwUg3.jpg'
    },
    {
        image:'https://i.imgur.com/gpu1t6v.jpg'
    },
    {
        image:'https://i.imgur.com/Y2Ux9Ou.jpg'
    },
    {
        image:'https://i.imgur.com/Kg26Io7.jpg'
    },
    {
        image:'https://i.imgur.com/d8H02g1.jpg'
    },
    {
        image:'https://i.imgur.com/pPxwbvT.jpg'
    },
    {
        image:'https://i.imgur.com/RUwU1Zd.jpg'
    },
];